# Generated by Django 4.2.4 on 2024-11-16 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=255)),
                ('creatividad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tema', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('Histotia', 'Histotia'), ('Logro', 'Logro'), ('Opnion de liderazgo', 'Opnion de liderazgo'), ('Pregunta', 'Pregunta'), ('Recomendacion', 'Recomendacion'), ('Reflexion', 'Reflexion'), ('Solicitud de ayuda', 'Solicitud de ayuda'), ('Sugerencia', 'Sugerencia')], max_length=255)),
                ('pensamientos', models.TextField()),
                ('ejemplo', models.TextField()),
                ('tono', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('red_social', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp')], max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('post_generado', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
