# Generated by Django 4.2.4 on 2024-11-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Historia', 'Historia'), ('Logro', 'Logro'), ('Opnion de liderazgo', 'Opnion de liderazgo'), ('Pregunta', 'Pregunta'), ('Recomendacion', 'Recomendacion'), ('Reflexion', 'Reflexion'), ('Solicitud de ayuda', 'Solicitud de ayuda'), ('Sugerencia', 'Sugerencia')], max_length=255),
        ),
    ]
